admin:
  access_log_path: "/tmp/admin_access.log"
  address:
    socket_address:
      address: "0.0.0.0"
      port_value: 9901
tracing:
  http:
    name: envoy.zipkin
    typed_config:
      "@type": type.googleapis.com/envoy.config.trace.v2.ZipkinConfig
      collector_cluster: jaeger
      collector_endpoint: "/api/v2/spans"
      shared_span_context: false
      collector_endpoint_version: HTTP_JSON
static_resources:
  listeners:

    -
      name: "{{cookiecutter._service_name}}-ingress"
      address:
        socket_address:
          address: "0.0.0.0"
          port_value: {{cookiecutter.proxy_port}}
      traffic_direction: INBOUND
      filter_chains:
        -
          filters:
            -
              name: "envoy.http_connection_manager"
              config:
                stat_prefix: "ingress"
                tracing: {}
                codec_type: "AUTO"
                route_config:
                  name: "{{cookiecutter._service_name}}-ingress-route"
                  virtual_hosts:
                    -
                      name: "{{cookiecutter._service_name}}-ingress-route"
                      domains:
                        - "*"
                      routes:
                        -
                          match:
                            prefix: "{{cookiecutter.route}}/metrics"
                          route:
                            cluster: "{{cookiecutter._service_name}}"
                          tracing:
                            overall_sampling:
                              numerator: 1
                              denominator: MILLION
                        -
                          match:
                            prefix: "{{cookiecutter.route}}"
                          route:
                            cluster: "{{cookiecutter._service_name}}"
                http_filters:
                  -
                    name: "envoy.router"
    {% if cookiecutter.call_another_service == "yes" -%}
    -
      name: "{{cookiecutter._service_name}}-egress"
      address:
        socket_address:
          address: "0.0.0.0"
          port_value: {{cookiecutter.egress_port}}
      traffic_direction: OUTBOUND
      filter_chains:
        -
          filters:
            -
              name: "envoy.http_connection_manager"
              config:
                stat_prefix: "egress"
                tracing: {}
                codec_type: "AUTO"
                route_config:
                  name: "{{cookiecutter._service_name}}-egress-route"
                  virtual_hosts:
                    -
                      name: "{{cookiecutter._service_name}}-egress-route"
                      domains:
                        - "*"
                      routes:
                        -
                          match:
                            prefix: "/"
                          route:
                            timeout: 3s
                            cluster: "{{cookiecutter.external_service_name}}"
                http_filters:
                  -
                    name: "envoy.router"
{% endif %}
  clusters:
      -
        name: "{{cookiecutter._service_name}}"
        connect_timeout: "0.25s"
        type: "strict_dns"
        lb_policy: "ROUND_ROBIN"
        hosts:
          -
            socket_address:
              address: "{{cookiecutter.service_address}}"
              port_value: {{cookiecutter.service_port}}
      {% if cookiecutter.call_another_service == "yes" -%}
      -
        name: "{{cookiecutter.external_service_name}}"
        connect_timeout: "0.25s"
        type: "strict_dns"
        lb_policy: "ROUND_ROBIN"
        hosts:
          -
            socket_address:
              address: "{{cookiecutter.external_service_address}}"
              port_value: {{cookiecutter.external_service_port}}
      {% endif %}
      -
        name: jaeger
        connect_timeout: 1s
        type: strict_dns
        lb_policy: round_robin
        load_assignment:
          cluster_name: jaeger
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: {{cookiecutter.jaeger_address}}
                    port_value: {{cookiecutter.jaeger_port}}
